### ISSUE TITLE
rust-analyzer issues

### ISSUE THREAD

**Issue by burrbull** [David-OConnor/stm32-hal#84]
I think this issue is more related for `rust-analyzer + VsCode` than this crate, but this is good example.

Trying to open repository with this `.vscode/settings.json`:
```json
{
  "rust-analyzer.check.allTargets": false,
  "rust-analyzer.check.targets": "thumbv7em-none-eabihf",
  "rust-analyzer.cargo.features": [
    "h735"
  ],
}
```
causes `pac` not found.

Same time in `lapce` with `.lapce/settings.toml`
```toml
[lapce-rust]
check.allTargets = false
check.targets = "thumbv7em-none-eabihf"
cargo.features = ["h735"]
```
all works fine.

I think the cause is that `stm32xxx` crates are optional.
